import json
import os

with open('src/assets/advanced-settings-meta.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

translation_dict = {
    # general
    "Session Name": "服务器名称 (Session Name)",
    "The name of your server as shown in the server browser.": "在服务器浏览器中显示的服务器名称。",
    "Server Map": "服务器地图 (Server Map)",
    "The map to use for this server instance. Select from common maps or enter a custom map name.": "此服务器实例使用的地图。从常见地图中选择或输入自定义地图名称。",
    "The Island": "孤岛 (The Island)",
    "Scorched Earth": "焦土 (Scorched Earth)",
    "The Center": "中心岛 (The Center)",
    "Ragnarok": "仙境 (Ragnarok)",
    "Aberration": "畸变 (Aberration)",
    "Lost Colony": "失落的岛屿 (Lost Colony)",
    "Max Players": "最大玩家数 (Max Players)",
    "The maximum number of players allowed on the server at once.": "服务器允许同时在线的最大玩家数。",
    "Server Password": "服务器密码 (Server Password)",
    "Players must enter this password to join your server. Leave blank for no password.": "玩家必须输入此密码才能加入服务器。留空则无密码。",
    "Admin Password": "管理员密码 (Admin Password)",
    "Required to use admin commands in-game. Keep this private.": "在游戏中使用管理员命令所需的密码。请保密。",
    "Enable Whitelist": "启用白名单",
    "Enable exclusive join mode - only whitelisted players can join the server. Uses PlayersExclusiveJoinList.txt file.": "启用独占加入模式 - 只有白名单上的玩家才能加入服务器。使用 PlayersExclusiveJoinList.txt 文件。",
    "Crossplay Platforms": "跨平台 (Crossplay Platforms)",
    "Select all platforms that should be able to join this server. Only players on the selected platforms will be able to connect.": "选择所有可以加入此服务器的平台。只有所选平台上的玩家才能连接。",
    "Launch Arguments": "启动参数 (Launch Arguments)",
    "Extra command-line arguments passed to the server on startup. Use for mod parameters like -MapModID=, -TotalConversionMod=, or other custom flags. Separate multiple arguments with spaces.": "启动时传递给服务器的额外命令行参数。用于模组参数，例如 -MapModID=、-TotalConversionMod= 或其他自定义标志。多个参数用空格分隔。",

    # rates
    "XP Multiplier": "经验倍率",
    "Multiplier for experience gain. Higher values = faster leveling, lower values = slower leveling.": "经验获取的倍率。值越高 = 升级越快，值越低 = 升级越慢。",
    "Override Official Difficulty": "覆盖官方难度",
    "Overrides the official difficulty value for the server.": "覆盖服务器的官方难度值。",
    "Difficulty": "难度",
    "Controls dino level and loot quality. Higher values increase difficulty.": "控制恐龙等级和战利品质量。值越高难度越大。",
    "Taming Speed Multiplier": "驯服速度倍率",
    "Multiplier for taming speed. Higher values = faster taming, lower values = slower taming.": "驯服速度的倍率。值越高 = 驯服越快，值越低 = 驯服越慢。",
    "Egg Hatch Speed Multiplier": "孵蛋速度倍率",
    "Multiplier for how quickly eggs hatch. Higher values = faster hatching, lower values = slower hatching.": "恐龙蛋孵化速度的倍率。值越高 = 孵化越快。",
    "Baby Mature Speed Multiplier": "幼龙成熟速度倍率",
    "Multiplier for how quickly babies mature. Higher values = faster maturation, lower values = slower maturation.": "幼龙成熟速度的倍率。值越高 = 成熟越快。",
    "Mating Interval Multiplier": "交配间隔倍率",
    "Multiplier for the time between allowed mating. Higher values = longer wait times, lower values = shorter wait times.": "允许交配之间的时间倍率。值越高 = 等待时间越长。",
    "Lay Egg Interval Multiplier": "产蛋间隔倍率",
    "Multiplier for the time between egg laying. Higher values = longer intervals between eggs, lower values = shorter intervals.": "产蛋之间的时间倍率。值越高 = 间隔越长。",
    "Mating Speed Multiplier": "交配速度倍率",
    "Multiplier for mating speed. Higher values = faster mating, lower values = slower mating.": "交配速度的倍率。值越高 = 交配越快。",
    "Baby Food Consumption Speed Multiplier": "幼龙食物消耗速度倍率",
    "Multiplier for how quickly babies consume food. Higher values = more food needed, lower values = less food needed.": "幼龙消耗食物速度的倍率。值越高 = 需要更多食物。",
    "Baby Cuddle Interval Multiplier": "幼龙留痕间隔倍率",
    "Multiplier for the time between baby cuddles. Higher values = longer intervals, lower values = shorter intervals.": "幼龙留痕（拥抱）之间的时间倍率。值越高 = 间隔越长。",
    "Baby Imprinting Stat Scale Multiplier": "幼龙留痕属性加成倍率",
    "Multiplier for how much imprinting affects stats. Higher values = stronger imprint bonuses, lower values = weaker imprint bonuses.": "留痕对属性影响程度的倍率。值越高 = 留痕奖励越强。",
    "Baby Cuddle Grace Period Multiplier": "幼龙留痕宽限期倍率",
    "Multiplier for the grace period after a missed cuddle. Higher values = longer grace period, lower values = shorter grace period.": "错过留痕后的宽限期倍率。值越高 = 宽限期越长。",
    "Baby Cuddle Lose Imprint Quality Speed Multiplier": "幼龙错过留痕掉量速度倍率",
    "Multiplier for how quickly imprint quality is lost after a missed cuddle. Higher values = faster imprint loss, lower values = slower imprint loss.": "错过留痕后失去留痕质量的速度倍率。值越高 = 失去越快。",
    "Baby Imprint Amount Multiplier": "幼龙单次留痕量倍率",
    "Multiplier for the amount of imprinting per cuddle. Higher values = more imprint per cuddle, lower values = less imprint per cuddle.": "每次留痕量的倍率。值越高 = 每次留痕增加的进度越多。",
    "Baby Max Interval Multiplier": "幼龙最大留痕间隔倍率",
    "Multiplier for the maximum allowed interval between baby cuddles. Higher values = longer max intervals, lower values = shorter max intervals.": "幼龙留痕之间允许的最大间隔倍率。值越高 = 最大间隔越长。",
    "Harvest Amount Multiplier": "采集量倍率",
    "Multiplier for resource harvest amount. Higher values = more resources per harvest, lower values = fewer resources per harvest.": "资源采集量的倍率。值越高 = 每次采集的资源越多。",
    "Dino Harvesting Damage Multiplier": "恐龙采集伤害倍率",
    "Multiplier for how much damage dinos do to harvestable resources. Higher values = more resources from dino harvesting, lower values = fewer resources.": "恐龙对可采集资源造成伤害的倍率。值越高 = 恐龙采集的资源越多。",
    "Player Harvesting Damage Multiplier": "玩家采集伤害倍率",
    "Multiplier for how much damage players do to harvestable resources. Higher values = more resources from player harvesting, lower values = fewer resources.": "玩家对可采集资源造成伤害的倍率。值越高 = 玩家采集的资源越多。",
    "Resources Respawn Period Multiplier": "资源刷新周期倍率",
    "Multiplier for how quickly resources respawn after being harvested. Higher values = slower respawn, lower values = faster respawn.": "资源被采集后刷新速度的倍率。值越高 = 刷新越慢，值越低 = 刷新越快。",
    "Crop Growth Speed Multiplier": "农作物生长速度倍率",
    "Multiplier for how quickly crops grow. Higher values = faster crop growth, lower values = slower crop growth.": "农作物生长速度的倍率。值越高 = 生长越快。",
    "Crop Decay Speed Multiplier": "农作物腐败速度倍率",
    "Multiplier for how quickly crops decay. Higher values = faster decay, lower values = slower decay.": "农作物腐败速度的倍率。值越高 = 腐败越快。",
    "Player Food Drain Multiplier": "玩家食物消耗倍率",
    "Multiplier for how quickly players get hungry. Higher values = get hungry faster, lower values = get hungry slower.": "玩家饥饿速度的倍率。值越高 = 饿得越快。",
    "Player Stamina Drain Multiplier": "玩家耐力消耗倍率",
    "Multiplier for how quickly players use stamina. Higher values = stamina drains faster, lower values = stamina drains slower.": "玩家消耗耐力速度的倍率。值越高 = 耐力消耗越快。",
    "Player Health Recovery Multiplier": "玩家生命恢复倍率",
    "Multiplier for how quickly players recover health. Higher values = faster health recovery, lower values = slower health recovery.": "玩家恢复生命值速度的倍率。值越高 = 恢复越快。",
    "Player Water Drain Multiplier": "玩家水分消耗倍率",
    "Multiplier for how quickly players get thirsty. Higher values = get thirsty faster, lower values = get thirsty slower.": "玩家口渴速度的倍率。值越高 = 渴得越快。",
    "Player Damage Multiplier": "玩家伤害倍率",
    "Multiplier for how much damage players deal. Higher values = more damage dealt, lower values = less damage dealt.": "玩家造成伤害的倍率。值越高 = 造成的伤害越多。",
    "Player Resistance Multiplier": "玩家抗性倍率",
    "Multiplier for how much damage players resist. Higher values = more damage resistance, lower values = less damage resistance.": "玩家抵抗伤害的倍率。值越高 = 伤害抗性越强（受到的伤害越少）。",
    "Dino Food Drain Multiplier": "恐龙食物消耗倍率",
    "Multiplier for how quickly dinos get hungry. Higher values = dinos get hungry faster, lower values = dinos get hungry slower.": "恐龙饥饿速度的倍率。值越高 = 饿得越快。",
    "Dino Stamina Drain Multiplier": "恐龙耐力消耗倍率",
    "Multiplier for how quickly dinos use stamina. Higher values = dino stamina drains faster, lower values = dino stamina drains slower.": "恐龙消耗耐力速度的倍率。值越高 = 耐力消耗越快。",
    "Dino Health Recovery Multiplier": "恐龙生命恢复倍率",
    "Multiplier for how quickly dinos recover health. Higher values = faster dino health recovery, lower values = slower dino health recovery.": "恐龙恢复生命值速度的倍率。值越高 = 恢复越快。",
    "Dino Damage Multiplier": "恐龙伤害倍率",
    "Multiplier for how much damage dinos deal. Higher values = more damage dealt by dinos, lower values = less damage dealt by dinos.": "恐龙造成伤害的倍率。值越高 = 造成的伤害越多。",
    "Dino Resistance Multiplier": "恐龙抗性倍率",
    "Multiplier for how much damage dinos resist. Higher values = more damage resistance for dinos, lower values = less damage resistance for dinos.": "恐龙抵抗伤害的倍率。值越高 = 伤害抗性越强（受到的伤害越少）。",
    "Day Cycle Speed Scale": "昼夜循环速度倍率",
    "Multiplier for the length of a full day/night cycle. Higher values = shorter cycles (faster time), lower values = longer cycles (slower time).": "完整昼夜循环长度的倍率。值越高 = 循环越短（时间越快）。",
    "Day Time Speed Scale": "白天速度倍率",
    "Multiplier for the length of daytime. Higher values = shorter days (faster daytime), lower values = longer days (slower daytime).": "白天长度的倍率。值越高 = 白天越短（白天时间流逝越快）。",
    "Night Time Speed Scale": "夜晚速度倍率",
    "Multiplier for the length of nighttime. Higher values = shorter nights (faster nighttime), lower values = longer nights (slower nighttime).": "夜晚长度的倍率。值越高 = 夜晚越短（夜晚时间流逝越快）。",
    "Fuel Consumption Interval Multiplier": "燃料消耗间隔倍率",
    "Multiplier for how quickly fuel is consumed by structures. Higher values = fuel lasts longer, lower values = fuel consumed faster.": "建筑消耗燃料速度的倍率。值越高 = 燃料持续时间越长。",
    "Global Spoiling Time Multiplier": "全局腐败时间倍率",
    "Multiplier for how quickly items spoil globally. Higher values = items spoil slower, lower values = items spoil faster.": "全局物品腐败速度的倍率。值越高 = 物品腐败越慢。",
    "Supply Crate Loot Quality Multiplier": "补给箱战利品质量倍率",
    "Multiplier for the quality of loot found in supply crates. Higher values = better loot quality, lower values = worse loot quality.": "补给箱中战利品质量的倍率。值越高 = 战利品质量越好。",
    "Fishing Loot Quality Multiplier": "钓鱼战利品质量倍率",
    "Multiplier for the quality of loot obtained from fishing. Higher values = better fishing rewards, lower values = worse fishing rewards.": "钓鱼获得战利品质量的倍率。值越高 = 钓鱼奖励越好。",
    "Oviraptor Egg Consumption Multiplier": "窃蛋龙吃蛋倍率",
    "Multiplier for how quickly Oviraptors consume eggs.": "窃蛋龙消耗蛋的速度倍率。",
    "Passive Tame Interval Multiplier": "和平驯服间隔倍率",
    "Multiplier for the interval between passive tame feeding. Lower values = more frequent feeding allowed.": "和平驯服喂食之间的间隔倍率。值越低 = 允许更频繁的喂食。",
    "Tamed Creature Food Drain Multiplier": "驯服生物食物消耗倍率",
    "Multiplier for how quickly tamed creatures get hungry. Higher values = get hungry faster, lower values = get hungry slower.": "已驯服生物饥饿速度的倍率。值越高 = 饿得越快。",
    "Tamed Creature Torpor Drain Multiplier": "驯服生物眩晕消耗倍率",
    "Multiplier for how quickly tamed creatures lose torpor. Higher values = faster torpor drain, lower values = slower torpor drain.": "已驯服生物失去眩晕值速度的倍率。值越高 = 眩晕值下降越快。",
    "Creature Count Multiplier": "生物数量倍率",
    "Multiplier for how many creatures spawn. Higher values = more creatures spawning, lower values = fewer creatures spawning.": "生物生成数量的倍率。值越高 = 生成的生物越多。",

    # structures
    "Structure Resistance Multiplier": "建筑抗性倍率",
    "Multiplier for how much damage structures resist. Higher values = structures take less damage, lower values = structures take more damage.": "建筑抵抗伤害的倍率。值越高 = 建筑受到的伤害越少。",
    "Structure Damage Multiplier": "建筑伤害倍率",
    "Multiplier for how much damage structures deal. Higher values = structures deal more damage, lower values = structures deal less damage.": "建筑造成伤害的倍率。值越高 = 建筑造成的伤害越多。",
    "Override Structure Platform Prevention": "覆盖平台建筑限制",
    "Allows structures on platforms that are normally prevented.": "允许在平台上放置通常被禁止的建筑。",
    "Force All Structure Locking": "强制锁定所有建筑",
    "Forces all structures to be locked by default.": "强制所有建筑默认处于锁定状态。",
    "Disable Structure Placement Collision": "禁用建筑放置碰撞",
    "Disables collision checks when placing structures.": "放置建筑时禁用碰撞检查。",
    "Disable Structure Decay PvE": "禁用 PvE 建筑衰变",
    "Disables structure decay in PvE mode.": "在 PvE 模式下禁用建筑衰变。",
    "Enable Extra Structure Prevention Volumes": "启用额外建筑禁止区域",
    "Enables extra volumes that prevent structure placement.": "启用阻止放置建筑的额外区域。",
    "Per Platform Max Structures Multiplier": "单个平台最大建筑数倍率",
    "Multiplier for the maximum number of structures allowed on platform saddles. Higher values = more structures on platforms.": "平台鞍上允许的最大建筑数量的倍率。值越高 = 平台上的建筑越多。",
    "Platform Saddle Build Area Bounds Multiplier": "平台鞍建造区域边界倍率",
    "Multiplier for the build area size on platform saddles. Higher values = larger buildable area.": "平台鞍上可建造区域大小的倍率。值越高 = 可建造区域越大。",
    "Max Platform Saddle Structure Limit": "平台鞍最大建筑限制",
    "Maximum number of structures that can be placed on a single platform saddle.": "单个平台鞍上可以放置的最大建筑数量。",
    "Max Gate Frames On Saddles": "鞍上最大恐龙门框数",
    "Maximum number of gate frames allowed on platform saddles.": "平台鞍上允许的最大门框数量。",
    "Structure Prevent Resource Radius Multiplier": "建筑阻止资源刷新半径倍率",
    "Multiplier for how far structures prevent resources from spawning. Higher values = larger no-resource zone around structures.": "建筑阻止资源生成距离的倍率。值越高 = 建筑周围无资源区越大。",
    "Structure Pickup Time After Placement": "放置后可拾取建筑时间",
    "Time in seconds after placement during which a structure can be picked up.": "放置后可以拾取建筑的时间（秒）。",
    "Structure Pickup Hold Duration": "拾取建筑按住持续时间",
    "Duration in seconds to hold the pickup button to pick up a structure.": "按住拾取按钮以拾取建筑的持续时间（秒）。",
    "Allow Integrated S+ Structures": "允许集成 S+ 建筑",
    "Enables the S+ (Structures Plus) integrated structures functionality.": "启用 S+（Structures Plus）集成的建筑功能。",
    "Allow Platform Saddle Stacking": "允许平台鞍堆叠",
    "Allows stacking structures on platform saddles beyond normal limits.": "允许在平台鞍上堆叠建筑，超出正常限制。",
    "Allow Cave Building PvE": "允许 PvE 洞穴内建造",
    "Allows building inside caves on PvE servers.": "允许在 PvE 服务器的洞穴内进行建造。",
    "Auto Destroy Old Structures Multiplier": "自动摧毁旧建筑倍率",
    "Multiplier for auto-destroying old structures. Set to 0 to disable. Higher values = faster auto-destroy.": "自动摧毁旧建筑的倍率。设置为 0 以禁用。值越高 = 自动摧毁越快。",
    "Max Structures In Range": "范围内最大建筑数",
    "Maximum number of structures allowed within a certain range. Prevents excessive structure spam.": "特定范围内允许的最大建筑数量。防止过度滥建。",
    "PvE Platform Structure Damage Ratio": "PvE 平台建筑伤害比率",
    "Multiplier for damage to structures built on platforms in PvE mode.": "PvE 模式下对建在平台上的建筑的伤害倍率。",

    # misc
    "PvE Mode": "PvE 模式",
    "Enable PvE mode in GameUserSettings.ini (companion to Server PvE).": "在 GameUserSettings.ini 中启用 PvE 模式（Server PvE 的配套设置）。",
    "Server PvE (Game.ini)": "服务器 PvE (Game.ini)",
    "The primary PvE switch for ASA. Writes ServerPVE=True to Game.ini. Enable this (alongside PvE Mode) to make your server fully PvE.": "ASA 的主要 PvE 开关。将 ServerPVE=True 写入 Game.ini。启用此项（与 PvE 模式一起）以使您的服务器完全成为 PvE。",
    "Show Floating Damage Text": "显示浮动伤害文本",
    "Shows floating damage numbers when dealing or receiving damage.": "造成或受到伤害时显示浮动伤害数字。",
    "Allow Third Person": "允许第三人称",
    "Allow players to toggle third-person camera view.": "允许玩家切换第三人称视角。",
    "Disable Imprint Dino Buff": "禁用留痕恐龙 Buff",
    "Disables the stat buff from imprinting on dinos.": "禁用恐龙留痕带来的属性增益。",
    "PvE Disable Friendly Fire": "PvE 禁用友军伤害",
    "Disables friendly fire in PvE mode.": "在 PvE 模式下禁用友军伤害。",
    "Allow Anyone Baby Imprint Cuddle": "允许任何人抚摸留痕幼龙",
    "Allow any player to cuddle and imprint any baby dino.": "允许任何玩家抚摸并留痕任何幼龙。",
    "Use Optimized Harvesting Health": "使用优化的采集生命值",
    "Enables optimized health for harvestable resources.": "为可采集资源启用优化的生命值。",
    "PvE Allow Tribe War": "PvE 允许部落战",
    "Allows tribe wars in PvE mode.": "允许在 PvE 模式下进行部落战。",
    "Allow Raid Dino Feeding": "允许喂食泰坦龙",
    "Allows feeding of raid dinos during raids.": "允许在团队副本期间喂食团队恐龙（如泰坦龙）。",
    "Disable Friendly Fire": "禁用友军伤害",
    "Disables friendly fire between players and tames.": "禁用玩家和驯服生物之间的友军伤害。",
    "PvE Allow Tribe War Cancel": "PvE 允许取消部落战",
    "Allows tribe wars to be cancelled in PvE mode.": "允许在 PvE 模式下取消部落战。",
    "Only Allow Specified Engrams": "仅允许指定的印迹",
    "Restricts crafting to only specified engrams.": "将制作限制为仅限指定的印迹技能。",
    "Disable Loot Crates": "禁用战利品宝箱",
    "Disables loot crate drops on the map.": "禁用地图上的战利品宝箱掉落。",
    "Increase PvP Respawn Interval": "增加 PvP 重生间隔",
    "Increases the respawn interval in PvP mode.": "增加 PvP 模式下的重生间隔时间。",
    "Allow Multiple Attached C4": "允许附着多个 C4",
    "Allows multiple C4 charges to be attached to a target.": "允许将多个 C4 炸药附着在目标上。",
    "Disable Weather Fog": "禁用天气雾",
    "Disables weather fog effects on the map.": "禁用地图上的天气雾效果。",
    "Prevent Offline PvP": "防止离线 PvP",
    "Prevents PvP actions against offline players/tribes.": "防止针对离线玩家/部落的 PvP 行为。",
    "Allow Unlimited Respecs": "允许无限洗点",
    "Allows players to respec their stats unlimited times.": "允许玩家无限次重置（洗点）他们的属性。",
    "Show Creative Mode": "显示创造模式",
    "Enables creative mode for all players.": "为所有玩家启用创造模式。",
    "Allow Platform Saddle Multi-Floors": "允许平台鞍多层地板",
    "Allows multiple floors on platform saddles.": "允许在平台鞍上建造多层地板。",
    "Use Corpse Locator": "使用尸体定位器",
    "Enables corpse locator for easier body recovery.": "启用尸体定位器，以便更轻松地找回尸体。",
    "Use Singleplayer Settings": "使用单人游戏设置",
    "Applies singleplayer balancing to the server.": "将单人游戏平衡应用于服务器。",
    "Flyers Ridable In Caves": "洞穴内可骑乘飞行生物",
    "Allows flying creatures to be ridden inside cave areas.": "允许在洞穴区域内骑乘飞行生物。",
    "Flyers Can Carry Wild Dinos In PVE": "允许飞行宠在 PVE 抓野生龙",
    "Allows flying creatures to pick up wild dinos and players on PvE servers.": "允许飞行生物在 PvE 服务器上抓取野生恐龙和玩家。",
    "Flyer Speed Levelling": "飞行生物速度升级",
    "Allows movement speed to be leveled on flying creatures.": "允许升级飞行生物的移动速度。",
    "Ground Speed Levelling": "陆地生物速度升级",
    "Allows movement speed to be leveled on ground creatures.": "允许升级陆地生物的移动速度。",
    "Server Max Tames": "服务器最大驯服数",
    "Maximum number of tamed creatures allowed server-wide. Set to 0 for unlimited.": "全服务器允许的最大驯服生物数量。设置为 0 则无限制。",
    "Max Tribe Tames": "部落最大驯服数",
    "Maximum number of tamed creatures allowed per tribe/player. Set to 0 for unlimited.": "每个部落/玩家允许的最大驯服生物数量。设置为 0 则无限制。",
    "No Creature Riding": "禁止骑乘生物",
    "When enabled, prevents players from riding any tamed creatures.": "启用后，防止玩家骑乘任何驯服的生物。",
    "Auto Unlock All Engrams": "自动解锁所有印迹",
    "Automatically unlocks all engrams for all players.": "自动为所有玩家解锁所有印迹技能。",
    "Hardcore Mode": "硬核模式",
    "Enables hardcore mode — players lose their character on death.": "启用硬核模式 — 玩家死亡时会失去其角色。",
    "Global Voice Chat": "全局语音聊天",
    "Enables global voice chat across the entire server.": "启用跨整个服务器的全局语音聊天。",
    "Proximity Chat": "附近语音聊天",
    "Enables proximity-based voice chat.": "启用基于距离的附近语音聊天。",
    "No HUD": "无 HUD",
    "Forces HUD to be disabled for all players.": "强制对所有玩家禁用 HUD（平视显示器）。",
    "Show Map Player Location": "地图显示玩家位置",
    "Shows player location on the in-game map.": "在游戏内地图上显示玩家位置。",
    "Server Crosshair": "服务器准星",
    "Enables server-side crosshair for all players.": "为所有玩家启用服务器端准星。",
    "Allow Hit Markers": "允许命中标记",
    "Enables visual hit markers when dealing damage.": "造成伤害时启用视觉命中标记。",
    "Admin Logging": "管理员日志",
    "Logs all admin commands to chat and server logs.": "将所有管理员命令记录到聊天和服务器日志中。",
    "Enable PVP Gamma": "启用 PVP 伽马值",
    "Allows players to adjust gamma in PVP mode.": "允许玩家在 PVP 模式下调整伽马值（亮度）。",
    "Disable PvE Gamma": "禁用 PvE 伽马值",
    "Prevents players from adjusting gamma in PvE mode.": "防止玩家在 PvE 模式下调整伽马值。",
    "Prevent Mate Boost": "防止配偶加成",
    "Disables the mate boost buff for tamed creatures.": "禁用驯服生物的配偶加成 Buff。",
    "Disable Imprinting": "禁用留痕",
    "Completely disables the imprinting system for baby creatures.": "完全禁用幼龙的留痕系统。",
    "Passive Defenses Damage Riderless Dinos": "被动防御伤害无骑乘者恐龙",
    "Allows passive defenses (plant species X, etc.) to damage riderless tamed dinos.": "允许被动防御（X食人花等）对没有骑乘者的驯服恐龙造成伤害。",
    "Auto Destroy Decayed Dinos": "自动摧毁腐坏恐龙",
    "Automatically destroys tamed dinos after they have decayed.": "驯服恐龙衰变后自动将其摧毁。",
    "Allow Custom Recipes": "允许自定义配方",
    "Allows players to create custom cooking recipes.": "允许玩家创建自定义烹饪配方。",
    "Clamp Resource Harvest Damage": "限制资源采集伤害",
    "Clamps the maximum harvest damage to prevent excessive resource gathering.": "限制最大采集伤害以防止过度收集资源。",
    "Item Stack Size Multiplier": "物品堆叠大小倍率",
    "Multiplier for item stack sizes. Higher values allow more items per stack.": "物品堆叠大小的倍率。值越高，每堆允许的物品越多。",
    "Disable Cryopod Fridge Requirement": "禁用低温舱冰箱要求",
    "When enabled, cryopods do not require a Cryofridge to preserve stored creatures.": "启用后，低温舱不需要低温冰箱来保存储存的生物。",
    "Disable Cryopod Enemy Check": "禁用低温舱敌人检查",
    "When enabled, players can deploy cryopods even when enemies are nearby.": "启用后，即使附近有敌人，玩家也可以部署低温舱。",
    "Allow Cryofridge On Saddle": "允许低温冰箱放置在鞍上",
    "Allows Cryofridges to be placed on platform saddles.": "允许将低温冰箱放置在平台鞍上。",
    "Max Number Of Players In Tribe": "部落最大玩家数",
    "Maximum number of players allowed in a single tribe. Set to 0 for unlimited.": "单个部落中允许的最大玩家数量。设置为 0 则无限制。",
    "Kick Idle Players Period": "踢出挂机玩家周期",
    "Seconds before idle players are kicked. Set to 0 to disable.": "踢出挂机玩家前的秒数。设置为 0 以禁用。",
    "Auto Save Period (Minutes)": "自动保存周期（分钟）",
    "How often in minutes the server auto-saves. Set to 0 to disable.": "服务器自动保存的频率（以分钟为单位）。设置为 0 以禁用。",
    "Prevent Offline PvP Interval": "防止离线 PvP 间隔",
    "Seconds before offline PvP protection activates after all tribe members log off.": "所有部落成员注销后，离线 PvP 保护激活前的秒数。",
    "Custom Recipe Effectiveness Multiplier": "自定义配方效果倍率",
    "Multiplier for the effectiveness of custom recipes.": "自定义配方效果的倍率。",
    "Custom Recipe Skill Multiplier": "自定义配方技能倍率",
    "Multiplier for the crafting skill bonus applied to custom recipes.": "应用于自定义配方的制作技能加成的倍率。",
    "Dino Turret Damage Multiplier": "恐龙炮塔伤害倍率",
    "Multiplier for how much damage turrets deal to creatures.": "炮塔对生物造成伤害的倍率。",

    # mods
    "Mod IDs (comma separated)": "模组 ID（逗号分隔）",
    "Enter CurseForge mod IDs, separated by commas.": "输入 CurseForge 模组 ID，用逗号分隔。"
}

for item in data:
    if "label" in item and item["label"] in translation_dict:
        item["label"] = translation_dict[item["label"]]
    if "description" in item and item["description"] in translation_dict:
        item["description"] = translation_dict[item["description"]]
    if "options" in item and isinstance(item["options"], list):
        for idx, opt in enumerate(item["options"]):
            if isinstance(opt, dict) and "display" in opt and opt["display"] in translation_dict:
                opt["display"] = translation_dict[opt["display"]]

with open('src/assets/advanced-settings-meta.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
